# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# ID checks
#
# ID01: check that identifiers only use lowercase and hyphens
# ID02: check that identifiers have a minimum length (specified in min_length
#       field)
# ID03: check for invalid ID patterns (empty, starting with hyphen or number,
#       containing dots or spaces)
#
# Example:
# ID01:
#    enabled: true
#    exclusions:
#        messages: []
#        files: []

# Content checks
#
# CO01: check for hard-coded brand names
#
# Example:
# CO01:
#    enabled: false
#    brands: []
#    exclusions:
#        messages: []
#        files: []
#
# CO02: check for prohibited words. Checks are case insensitive.
#
# Example:
# CO02:
#    enabled: false
#    words: []
#    exclusions:
#        messages: []
#        files: []

# Typography checks
#
# TE01: single quote instead of apostrophe for genitive (foo's)
# TE02: wrong apostrophe for genitive (foo‘s)
# TE03: single quotes ('foo')
# TE04: single double quotes ("foo")
# TE05: 3 dots for ellipsis ("...")
#
# Only accepts exceptions per string, not file
# Example:
# TE01:
#     exclusions:
#         messages: []

# Syntax checks
#
# Specify if syntax features are disabled. If the config is missing, it
# will considered as enabled.
#
# Example:
# SY01:
#     disabled: true
#
# SY01: terms
# SY02: message references
# SY03: term references
# SY04: variants
# SY05: attributes
# SY06: variable references

# Comments
#
# Specify if checks for group and resource comments are enabled or disabled. If
# the config is missing, the rule will be enabled.
#
# Example: GC: disabled: true
#
# GC: group comments (default: enabled) RC: resource comments (default: enabled)
#
# Check for variable references in comments associated to a message. Disabled by
# default.

# VC: variable comments (default: disabled)
#
# To enable: VC: disabled: false

# PS: placeable style checks (default: disabled)
#
# PS01: placeables (variables, comment and term references ) preceded and
#       followed by exactly one space ({ $var }, not {$var})
#
# To enable: PS01: disabled: false

---
ID01:
    enabled: false
    exclusions:
        messages: []
        files: []
ID02:
    enabled: false
    min_length: 9
    exclusions:
        messages: []
        files: []
ID03:
    enabled: false
    exclusions:
        messages: []
        files: []
CO01:
    enabled: false
    brands: []
    exclusions:
        messages: []
        files: []
